theme: jekyll-theme-slate
title: Quality Assurance Engineer (Manual / Automation)
description:# [Email](andrew.semenov.sas@gmail.com) | [Telegram](https://t.me/andrewsemenovsas) | [Linkedin](https://linkedin.com/in/andrew-semenov-sas) | [Resume / CV](https://drive.google.com/file/d/1_FlaGj-JcFYpTy5ahL5Zzzem0-fhJ3Qz/view)
show_downloads: false
