theme: jekyll-theme-slate
title: <h2 style="color:#fff; background: none;">Quality Assurance Engineer (Manual / Automation)</h2>
description:  <a href="mailto:andrew.semenov.sas@gmail.com" style="color:#fff;">andrew.semenov.sas@gmail.com</a><span> | </span> 
              <a href="https://t.me/andrewsemenovsas" style="color:#fff;">Telegram</a> <span> | </span> 
              <a href="https://linkedin.com/in/andrew-semenov-sas" style="color:#fff;">Linkedin</a> <span> | </span> 
              <a href="https://drive.google.com/file/d/1_FlaGj-JcFYpTy5ahL5Zzzem0-fhJ3Qz/view" style="color:#fff;">Resume / CV</a> 
show_downloads: false
