theme: jekyll-theme-slate
title: <h1 style="color: white">Quality Assurance Engineer (Manual / Automation)</h1>
description:  <a href="mailto:andrew.semenov.sas@gmail.com">Send me e-mail</a> <span> | </span> 
              <a href="https://t.me/andrewsemenovsas">Telegram</a> <span> | </span> 
              <a href="https://linkedin.com/in/andrew-semenov-sas">Linkedin</a> <span> | </span> 
              <a href="https://drive.google.com/file/d/1_FlaGj-JcFYpTy5ahL5Zzzem0-fhJ3Qz/view">Resume / CV</a> 
show_downloads: false
